- hosts: k8s_cluster
  become: true
  any_errors_fatal: true
  roles:
    - role: freehck.k8s
      tags:
        - k8s

- hosts: kube1
  become: true
  vars:
    - k8s_namespace: "default"
    - cassandra_operator_helm_release: "cassandra-operator"
  roles:
    - role: k8s-cassandra-operator
    - role: k8s-rancher-local-path-provisioner
    - role: k8s-cassandracluster
